# before_script:
  # - "sh -e /etc/init.d/xvfb start"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo sh -e travis-python-setup.sh"
script: "DISPLAY=:99.0 bundle exec rake jasmine_core_spec && tox"

rvm:
  - "1.9.3"
